var categories = [
  { name: 'statecharts and routes',
    color: 'blue',
    keywords: ['statechart', 'state chart', 'state', 'substate', 'route'] },
  { name: 'testing',
    color: 'red',
    keywords: ['test', 'qunit' ] },
  { name: 'browsers and html',
    color: 'yellow',
    keywords: ['safari', 'ie', 'internet explorer', 'chrome', 'ff', 'firefox', 'opera', 'iphone', 'ipad', 'desktop', 'mobile', 'browser', 'xhtml', 'html', 'html5', 'xss'] },
  { name: 'runtime and such',
    color: 'grey',
    keywords: ['observable', 'observer', 'responder', 'bind', 'enumerable', 'runtime', 'foundation', 'array', 'manyarray', 'childarray', 'prototype', 'controller', 'runloop', 'run loop', 'property'] },
  { name: 'css and themes',
    color: 'green',
    keywords: ['font', 'css', 'zindex', 'ace', 'sass'] },
  { name: 'views and events',
    color: 'cyan',
    keywords: ['view', 'button', 'label', 'checkbox', 'pane', 'menu', 'list', 'row', 'column', 'item', 'listitem', 'disclosure', 'layout', 'width', 'height', 'top', 'bottom', 'left', 'right', 'centerx', 'centery', 'border', 'layer', 'frame', 'scroll', 'picker', 'container', 'theme', 'icon', 'toggle', 'touch', 'click', 'drag', 'drop', 'mousewheel', 'event', 'mouse', 'render', 'aria', 'chance' ] },
  { name: 'models, store, and datasource',
    color: 'magenta',
    keywords: ['model', 'recordattribute', 'record', 'attribute', 'datastore', 'store', 'datasource', 'quer', 'xhr', 'request', 'response', 'ajax'] },
  { name: 'docs',
    color: 'rainbow',
    keywords: ['doc', 'typo'] },
  { name: 'handlebars and render delegates',
    color: 'inverse',
    keywords: ['handlebar', 'mustache', 'template', '{{', '}}', '#collection', 'render delegate', 'delegate'] }
];

exports.categories = categories;